### ISSUE TITLE
publish September, 2016 column

### ISSUE THREAD

**Issue by whit537** [whit537/openorg#1]
Probably an introduction?

"I'm Chad. I work on Gratipay and COS and tried OCI in the past."

#### Live

https://opensource.com/open-organization/16/9/openness-means-to-what-end

#### Drafts

- [**Working Draft**](https://docs.google.com/document/d/1RnMUJ_OI6jWQhAVJVuRxhKCROWExC1KqmY0wrh7BIK0/edit?usp=sharing)
- [Draft 3](https://docs.google.com/document/d/1kT_My-T9bMkbKtP1geOLnPNEGyH4k64wt5YcbeYERks/edit?usp=sharing)
- [Draft 2.1](https://docs.google.com/document/d/1KbHixmiMvfX2uhf7M9YOs2_qEiw373GQWouN8NhFork/edit?usp=sharing)
- [Draft 1](https://docs.google.com/document/d/1x8o9m3xSRzxKfYDJ5xrtbm-T7FRi296miosiKfOnB_8/edit?usp=sharing)

**Comment by whit537** [comment]
At this point I'm thinking of using the column to explore strategy ideas related to https://github.com/gratipay/inside.gratipay.com/issues/755 over the course of the year.

I'm thinking about front-loading the [ladder of love](http://inside.gratipay.com/big-picture/brand/), so that I can refer to it in later installments for context.

**Comment by whit537** [comment]
I started an etherpad to track column ideas:

https://public.etherpad-mozilla.org/p/openorg-column-ideas

**Comment by whit537** [comment]
I kind want to jump right in rather than wasting a post on introducing myself. That's what my bio is for.

**Comment by semioticrobotic** [comment]
I second the idea of composing something about the ladder of love. I think Gratipay's story here has broader purchase when the angle is something like: "How do you visualize your core values?" I'm thinking here of the way Gratipay explicitly relies on a ladder metaphor for expressing the relationships between its core values (with a nod to Asimov, my favorite!). At Red Hat, the metaphor is a scale or balance (see p. 111 of _The Open Organization_). These devices are important because they stress the fact that _more important_ than values are the _dynamics and connections_ between the values.

**Comment by whit537** [comment]
Two more ideas (noted on the [pad](https://public.etherpad-mozilla.org/p/openorg-column-ideas)):

- **The end of open source is the beginning**—Open-source is not what it used to be, and that's a good thing.
- **Platform Cooperativism, open-source, and nonprofits**—Non-profits can be a good legal structure for [platform cooperatives](www.shareable.net/blog/a-shareable-explainer-what-is-a-platform-co-op), because open-source demonstrates a new kind of ownership.

**Comment by whit537** [comment]
Okay @semioticrobotic, here's [500 words for you](https://docs.google.com/document/d/1x8o9m3xSRzxKfYDJ5xrtbm-T7FRi296miosiKfOnB_8/edit?usp=sharing). Didn't go with the Ladder of Love yet, saving that for a future post. This is an attempt to identify some of the folks I want to be in conversation with over this next year. Let me know how it reads to you! Or make edits ... I sent you an invite to edit the doc. :)

**Comment by whit537** [comment]
(@timothyfcook also has edit perms.)

**Comment by semioticrobotic** [comment]
Excellent! I will read this in the next day or two and will certainly send you feedback. Very excited to see your first column taking shape.

**Comment by whit537** [comment]
Okay! Soooooooo ... I've been working for the past couple years to figure out my "voice" (if you will) vis-a-vis "diversity issues" (if you will). **tl;dr**, Draft 1 ain't it. To be honest, I've been having heart palpitations all night, up until talking it through with @JessWhit just now. ;-)

(P.S. For a deeeeeeeeep dive, see the Geek Feminism wiki on the [Gittip crisis](http://geekfeminism.wikia.com/wiki/Gittip_crisis), and the internally infamous https://github.com/gratipay/inside.gratipay.com/issues/319.)

Please consider Draft 1 to be scrapped. Instead of enumerating the conversations I want to be a part of, I'm now leaning back toward the ladder of love idea, that is, stating what I'm _for_ in relation to open organizations, and then foraying out from there to engage with this or that person, idea, or event as the year progresses.

Thanks for working through this with me today, @timothyfcook, and thanks for your understanding, @semioticrobotic. :-)

**Comment by semioticrobotic** [comment]
Draft? What draft? Oh, that? Never saw it.

Talk to you soon, @whit537.

**Comment by whit537** [comment]
Okay @semioticrobotic @timothyfcook, here's [Draft 2](https://docs.google.com/document/d/1RnMUJ_OI6jWQhAVJVuRxhKCROWExC1KqmY0wrh7BIK0/edit?usp=sharing), about the Ladder of Love. ❤️ 🌳

**Comment by semioticrobotic** [comment]
Going to be a great first column, @whit537! I made some edits and suggestions. See what you think.

**Comment by whit537** [comment]
Thanks for the revisions, @semioticrobotic. I'm learning how best to work with Google Docs over here ... I've made another pass through, snapshotting a [Draft 3](https://docs.google.com/document/d/1kT_My-T9bMkbKtP1geOLnPNEGyH4k64wt5YcbeYERks/edit?usp=sharing) for posterity. Let's keep collaborating on the [working draft](https://docs.google.com/document/d/1RnMUJ_OI6jWQhAVJVuRxhKCROWExC1KqmY0wrh7BIK0/edit?usp=sharing).

**Comment by semioticrobotic** [comment]
> I'm learning how best to work with Google Docs over here ...

You and me both, @whit537. But we seem to be doing alright. I really like your recent round of revisions. I will take another pass, but I believe it's getting very close.

**Comment by whit537** [comment]
Got your email with the link to the page proof, @semioticrobotic. I made two very minor changes:

 - I made the third paragraph a `blockquote`.
 - "to use Brook" &rarr; "to borrow Brook"

With that, I am ready to go with this whenever it fits into the publishing schedule!

**Comment by semioticrobotic** [comment]
Thanks, @whit537. I thought posting here may have been superfluous because you're the only one who can actually access the page proofs (they're tied to your account). Really glad to see this wrap up so nicely. What a great debut. I will let you know when we have a firm publication date for the column.

**Comment by whit537** [comment]
@semioticrobotic I'm fine leaving the link out of this thread until it's live (though if we trust the authentication on OpenSource.com, is it a problem to have the link out in public? :). I just wanted to circle back here to keep our conversation in one place. :-)

Glad we're ready to move forward! Thanks for your help, the piece is much stronger now than before you got your hands on it.

**Comment by semioticrobotic** [comment]
> though if we trust the authentication on OpenSource.com, is it a problem to have the link out in public? :)

Well, you certainly have a point. But my concern is less about authentication and security and more about simply creating confusion. I didn't want to post what looks like—for all intents and purposes to anyone but you and me—a dead link, only to invite a torrent of "Hey FYI the link is broken" notifications and emails from curious and perspicacious onlookers. Happy to post here when it's live, though. Obviously no sweat there.

**Comment by whit537** [comment]
Hah! I think you're giving us too much credit. I'm pretty sure @timothyfcook is our singular curious and perspicacious onlooker, and that he will understand. ;-)

**Comment by semioticrobotic** [comment]
Just a note that this is likely going live tomorrow!

**Comment by whit537** [comment]
Woo-hoo! Thanks, @semioticrobotic! 💃

https://opensource.com/open-organization/16/9/openness-means-to-what-end

Closing ...

**Comment by whit537** [comment]
I wonder, though, whether "Gratipay makes 'love'" is the best start to a headline? 😶
