### ISSUE TITLE
Fix image formatting on OpenOrg website

### ISSUE THREAD

**Issue by timothyfcook** [whit537/openorg#3]
https://opensource.com/open-organization/resources/meet-ambassadors

**Comment by whit537** [comment]
Waddya think, @semioticrobotic? Any chance of this? We're looking at the aspect ratio of the ambassador photos on that page:

![screen shot 2016-08-22 at 5 07 01 pm](https://cloud.githubusercontent.com/assets/134455/17871737/dbe19de2-688a-11e6-9f4a-1618c0089722.png)

vs. the original, [e.g.](https://opensource.com/sites/default/files/resize/images/business-uploads/jonob_2_sq-100x100.jpg):

![screen shot 2016-08-22 at 5 07 18 pm](https://cloud.githubusercontent.com/assets/134455/17871752/ea0cb6b8-688a-11e6-947d-8f9e9114bf8a.png)

**Comment by timothyfcook** [comment]
Is their site open-source? Can make a PR.

**Comment by whit537** [comment]
It's a Drupal site, so the content is not open-source code afaik.

**Comment by semioticrobotic** [comment]
Hello to you both! I checked the aspect ratio on the photos and fixed a few that were wonky. But Jono's looks good to me. No?

**Comment by whit537** [comment]
Thanks @semioticrobotic! Jono's is definitely wonky. Looking into this further, I just discovered that the  element inspector in the Chrome dev tools (right-click, "Inspect Element") shows both the displayed and "natural" size of an image (unfortunately Firefox's inspector doesn't seem to have this feature). Here's what I'm seeing:

![screen shot 2016-08-23 at 9 22 36 am](https://cloud.githubusercontent.com/assets/134455/17893316/4df3f50a-6913-11e6-9b32-eb52762e4a07.png)

That's a displayed size of 88 x 100, whereas the natural size is 100 x 100.

Does that give you something to go on?

**Comment by semioticrobotic** [comment]
Very strange indeed. I'm seeing something different in Firefox.
![screenshot from 2016-08-23 09 55 41](https://cloud.githubusercontent.com/assets/19554310/17894574/d1ab0394-6917-11e6-9471-6108fac63b14.png)

**Comment by whit537** [comment]
In Firefox I just discovered that if I right-click and select "View Image Info" then I can see the info about the displayed and original dimensions—"100px × 100px (scaled to 86px × 98px)" in Jono's case.

--------------

![screen shot 2016-08-23 at 9 58 07 am](https://cloud.githubusercontent.com/assets/134455/17894696/3b7f663e-6918-11e6-93ff-de710263f90f.png)

**Comment by semioticrobotic** [comment]
And in my Firefox, it's different still.
![screenshot from 2016-08-23 10 01 43](https://cloud.githubusercontent.com/assets/19554310/17894798/ab6d0780-6918-11e6-8e4f-354de9b42be3.png)

**Comment by whit537** [comment]
Interesting! 😳

I'm running FF 47.0 on Mac OS 10.10.5. You?

**Comment by semioticrobotic** [comment]
Firefox 38.4 on RHEL 7.1 here.

**Comment by semioticrobotic** [comment]
(Jono's going to love this thread, by the way.)

**Comment by whit537** [comment]
> (Jono's going to love this thread, by the way.)

cc: @jonobacon ;-)

**Comment by whit537** [comment]
I tried resizing the browser window to see if it's related to layout width, but I don't see that it is.

> Firefox 38.4

That's an old Firefox. Current is 48.0.1 (I just updated; same results). Can you update Firefox and try again?

**Comment by semioticrobotic** [comment]
It's probably my version of Firefox, yes. Unfortunately I can't update yet because this is the latest sable version in the repositories (I'm on the employee build of RHEL7). But I'll ask a co-worker for assistance.

**Comment by semioticrobotic** [comment]
Any better, @whit537? Tried to come at the problem another way (thanks to sage advice from @jehb).

**Comment by jonobacon** [comment]
I am glad I can be an inspiration. :-)

**Comment by timothyfcook** [comment]
good enough for me! nice work team.
