### ISSUE TITLE
have more video conversations

### ISSUE THREAD

**Issue by whit537** [whit537/openorg#4]
@jhibbets on [Twitter](https://twitter.com/nerdworldorder/status/771785835180089344) (following on from #2):

> Would you like to have more conversations like about #OpenOrg, open leadership, etc? If so, is video preferred?

**Comment by whit537** [comment]
@webmaven:

> In general, I'd prefer audio only, unless there are visual aids such as illustrative slides.

@whit537

> Possibly? Qs would be a) time commitment, and b) diversity of voices. I do prefer raw video (can edit → audio, &c). Let's follow up in https://github.com/whit537/openorg/issues/4?

**Comment by semioticrobotic** [comment]
Just for some extra context:

Multiple members of our community have expressed to us a desire for speaking opportunities, roundtables, webcasts, and the like, and for some time we've been wrestling with the best way to facilitate these. One thought we had—and this cuts to @jhibbets initial query—is coordinating some kind of regular or semi-regular series of webcasted conversations of/between/with the ambassadors and special guests. But we're asking the same question you are: What kind of investment (in terms of time and resources) would this require? And can we cultivate and include a sufficient variety of voices and perspectives each time? What's the unifying theme or impetus? And how do we market and/or promote it all. Important questions, to be sure.

**Comment by whit537** [comment]
Thanks @semioticrobotic. One thing I'll say is that I personally prefer to only do raw, livestreamed video calls, even if—_especially_ if—the intention is to edit them down in some way. I think of the raw version as the "source code," and it think it's good to have the source available for anyone wishing to dive deeper.

**Comment by webmaven** [comment]
further context for my Twitter reply (I am nerdworldorder there) is that I really would prefer an audio-only version available (ideally via a subscribable feed like most podcasts.). Some people add value when you see them talking, but often the video component is just distracting whether from background events, bad lighting, body language (I personally tend to alternate between slouching and lunging at the camera, for example), expressive hand gestures at the edges of the field of view, etc.

**Comment by semioticrobotic** [comment]
All great to know. Thanks to you both.
