### ISSUE TITLE
publish October, 2016 column

### ISSUE THREAD

**Issue by whit537** [whit537/openorg#5]
## Drafts
- [**working draft**](https://docs.google.com/document/d/1CtBzYu2pVQGOTQ_-YwM32Ekp61cXvtbH-WeNsFeEmjU/edit?usp=sharing)
- [draft 1](https://docs.google.com/document/d/1_s4yyn0m-OIN8yypqynO9lQwEcrXjrl7iEWUYNEVGfI/edit?usp=sharing)
## Ideas

Looking at [my notes](https://public.etherpad-mozilla.org/p/openorg-column-ideas), I am thinking that I'd like to use October's column to engage with the platform cooperativism conversation. Notes snapshot:

> http://www.shareable.net/blog/a-shareable-explainer-what-is-a-platform-co-op
> 
> Nonprofits can be a good legal structure for platform cooperatives. Open-source shows how we can implement ownership in a meaningful sense on top of legal structure.
> 
> https://github.com/gratipay/inside.gratipay.com/issues/72#issuecomment-230070971
> 
> https://opensource.com/open-organization/15/9/learn-from-co-ops
> 
> http://open.coop/2016/06/23/not-a-co-op-not-a-platform-co-op/ ... ooh! Gratipay is mentioned! :-)

**Comment by whit537** [comment]
Shareable published their explainer last month, and the next [Platform Cooperativism](http://platformcoop.net/) conference is coming up in November, so this would be timely. I want to explore the idea of "virtual ownership" or "virtual cooperativism"—ownership in a supra-legal sense.

**Comment by whit537** [comment]
But I may bump that to November, because I also have something I want to say ahead of the open org ambassador meeting coming up next month ...

**Comment by whit537** [comment]
I wrote a draft this morning, but I need to run it by a couple folks privately first.

**Comment by semioticrobotic** [comment]
Music to my ears. Looking forward to reading it.

**Comment by whit537** [comment]
Alright, I've tabled my first draft for a later column. For this month I've drafted a separate piece on the [free rider problem in open source](https://docs.google.com/document/d/1CtBzYu2pVQGOTQ_-YwM32Ekp61cXvtbH-WeNsFeEmjU/edit?usp=sharing). Let me know how it looks, @semioticrobotic!

**Comment by semioticrobotic** [comment]
Nice! Thanks, @whit537. I will take a look as soon as possible. Looking forward to it.

**Comment by semioticrobotic** [comment]
Love this one! Such a critical topic. I made a few changes and suggestions for elaboration i a few areas, @whit537.

**Comment by whit537** [comment]
Thanks @semioticrobotic, I'll take a look ...

**Comment by whit537** [comment]
I've worked through the easiest edits, leaving a few that will take a little more thought. Hopefully tomorrow!

**Comment by whit537** [comment]
Not gonna get to this today.

**Comment by semioticrobotic** [comment]
Hey, no worries! Let it marinate over the weekend and we'll revisit it again next week.

**Comment by whit537** [comment]
Thanks, @semioticrobotic. We're close, that's for sure. Where do you see this fitting in the publishing schedule?

**Comment by semioticrobotic** [comment]
Tough to tell, to be perfectly honest. The scheduled fluctuates weekly as we balance what we have in the queue what we've already published that week, etc. But when we've got a final draft in hand, we can zero-in on a window. No rush.

**Comment by whit537** [comment]
Alright, @semioticrobotic. I finally finished https://github.com/gratipay/inside.gratipay.com/issues/409, and I've revised [the draft](https://docs.google.com/document/d/1CtBzYu2pVQGOTQ_-YwM32Ekp61cXvtbH-WeNsFeEmjU/edit?usp=sharing). Let me know how it looks!

**Comment by semioticrobotic** [comment]
Love the second draft. Made a few comments and suggestions in-line (really just helping readers parse the economic distinctions you're making), so see what you think.

**Comment by whit537** [comment]
Back to you, @semioticrobotic! I (re)combined paragraphs in a couple instances where I thought splitting them broke up the flow of the argument, and I tried to keep a narrower focus on open source _software_ in the final paragraph since that's the scope of the piece overall. Other than that, I believe I accepted all of your revisions. The point about parking garages not being CPRs was particularly helpful, thanks.

Are we there yet? :)

**Comment by semioticrobotic** [comment]
All looks good to me, @whit537. Thanks for your hard work. Cut! Print!

**Comment by whit537** [comment]
Where are we at in the queue on this, @semioticrobotic? Now that we're into November, perhaps I will work on my next column for December?

**Comment by semioticrobotic** [comment]
I just scheduled this, actually! It's set for two weeks from now. Sorry for the delay, @whit537.

**Comment by whit537** [comment]
@semioticrobotic Nice! And no worries, we were both busy. ;-)

**Comment by whit537** [comment]
https://opensource.com/open-organization/16/11/open-source-free-rider-problem

Top 10! 💃
