### ISSUE TITLE
prepare a lightning talk for ATO 2016

### ISSUE THREAD

**Issue by whit537** [whit537/openorg#6]
[**Working draft**](https://docs.google.com/document/d/1YLqskSd0SrSqaUWAVhELY0lFZ3tNaeQ3LFU6ES3a_5A/edit?usp=sharing)
---

I'm scheduled to give a lightning talk at All Things Open (https://github.com/gratipay/inside.gratipay.com/issues/757). What should I do?

From @jhibbets:

> I was hoping you could talk about working in the open with your experience at Gratipay. I'm open to suggestions on what your talk could be about, but it must be in the realm of open source in order to fit with our content. I want to give you some flexibility, because I know you've got a few different directions you could take this if you want to have fun with us on the main stage.
> 
> [M]y plan is to collect title talks and bios soon. I would need to collect slides by October 14. Also, our plan is to record the talks and publish them on Opensource.com after the conference.

**Comment by jhibbets** [comment]
I'll be sending out more details this week!
Jason

**Comment by whit537** [comment]
@jhibbets Maybe satire?

-------------------

# Draft 1

Hi, I'm Chad Whitacre, I'm the founder of a payments company called Gratipay, and I'm also part of the Opensource.com open organization ambassadors program. My goal in the next five minutes is to introduce you to the idea of an open organization, and convince you that it's an important idea.

As Jim Whitehurst describes in his 2015 book, open organizations "engage participative communities both inside and out." Let me illustrate by example.

Red Hat is an open organization. My own company, Gratipay, is an open organization. But did you know that Mylan is also an open organization? They're the ones that make EpiPens. Here's a Tweet from CEO Heather Bresch back in 2007:

[fake Twitter screenshot]

> I'd like to increase my compensation by 600% over the next few years. Any ideas?

Another example you may not know about is Wells Fargo. Here's the public GitHub ticket where CEO John Stumpf first discovered the idea that made his bank what it is today:

[fake GitHub screenshot]

> I've got it! Have the peons make *fake* accounts!

Hopefully those two examples start to give you an idea of the power of open organizations. You never know where the next big idea is going to come from!

Now let's talk about _why_ this idea is so important.

One word: accountability.

If there's one thing we can all agree on, it's that the person who dies with the most cash wins. Thankfully, amassing wealth for ourselves as executives aligns with the fundamental purpose of our organizations, which is to passively amass wealth for our other shareholders as well, regardless of the social impact of our organization.

_Open_ organizations give us a way to hold our leaders _accountable_ for hoarding as much wealth as possible.

If Mylan were closed, just think what Heather would have been able to get away with! After going to all the trouble of creating a monopoly and lobbying congress to help mandate EpiPens in schools, imagine if she had simply acquiesced to paying taxes, or had kept the price of EpiPens stable! Making her decisions openly and publicly not only gives her access to the best ideas, it incentivizes her to follow through on them.

Same with Wells Fargo. If John Stumpf were operating behind closed doors, he never would have been emboldened to make the right choice, however difficult, and sacrifice the lowest-paid two percent of his workforce for the greater good.

Instead, because Wells and Mylan are open, Heather and John _knew_ they would be held accountable for hoarding as much wealth as possible for themselves and their fellow shareholders, and they acted accordingly.

Now, openness is not "magic pixie dust." Heather Bresch and John Stumpf are leaders of integrity. That they choose to lead their organizations openly is more an effect of their character than a cause. Fundamentally honest leaders like Heather and John _want_ to be held accountable for their actions. Open organizations enable us to do just that, and that's why they are so important.

Open organizations like Mylan and Wells Fargo are driving the future, together with Red Hat, Gratipay, and others. To join us in this movement, follow and engage with the open organization channel on opensource.com. Thank you for your time!

**Comment by kaguillera** [comment]
😱  😲

**Comment by whit537** [comment]
Cross-posting from https://github.com/gratipay/inside.gratipay.com/issues/757#issuecomment-251278168:

> Main stage aspect ration = 16:9

-----------

> Hello lightning talks speakers!
>
I have a few important details for you, please let me know if you have
any questions between now and then. Thanks again for speaking.
>
1) In order to promote your talk and add it to the conference schedule,
please complete this short form by October 7
>
https://docs.google.com/forms/d/e/1FAIpQLSdvuPSxS0-cqAQ9xSUqRUHS58svZT_o-0BqYpgiiAUiFRYhGg/viewform
>
2) We have a very tight schedule on October 27. Talks will be strictly
limited to 5 minutes. We have 1 minute between talks to transition. In
order to help us stay on time, we ask that all speakers arrive at the
front of the main stage at 12:15 pm. We will have reserved seating for
all of you. We will also have a visible timer for you. (Grab a boxed
lunch and join us in the main ballrooms.)
>
3) Slides are due on or before October 17. You can submit them to me or
add them to the following Dropbox:
https://www.dropbox.com/home/Events/All%20Things%20Open%202016
>
Submit your slides in PDF format so we don't lose any formatting you
require.
>
Pro Tips:
- Include your Twitter handle and the conference hashtag, #ATO2016 on
every slide
>
4) Practice, practice, practice. For those of you that have experience
with lightning talks, you know these 5 minutes will go by fast. Be sure
to get a couple of dry-runs under your belt.
>
5) Talks will be recorded and Opensource.com will publish them on our
YouTube channel under a Creative Commons license.
>
We're excited!
Jason

**Comment by whit537** [comment]
@JessWhit thinks I would need to try out [Draft 1](https://github.com/whit537/openorg/issues/6#issuecomment-249638475) live on a few folks to see if the device works or falls flat.

**Comment by whit537** [comment]
@jhibbets Do you provide the laptop for lightening talk slides or do I need to bring one?

**Comment by jhibbets** [comment]
slides will be run from the back of the room, so we'll have that covered.

**Comment by whit537** [comment]
Awesome, thanks. I am thinking that I don't want to go the satire route, or at least dial it way back to a small part of the talk. Getting a new headshot tonight, aiming to get that form filled out tomorrow.

**Comment by whit537** [comment]
@jhibbets Is tomorrow hard-and-fast for a headshot or can I get you one next week? Just had a photo session but need some processing time, lmk ...

**Comment by jhibbets** [comment]
Next week is fine.

**Comment by whit537** [comment]
Awesome, thanks. Still aiming for the rest of the form tomorrow.

**Comment by whit537** [comment]
@jhibbets Would it be appropriate to use my lightning talk to pitch Gratipay as a solution to the free rider problem in open source?

**Comment by whit537** [comment]
Basically, explain the free rider problem in open source for four minutes (introduce [excludability and rivalrousness](https://en.wikipedia.org/wiki/Public_good#Definition_matrix), non-excludable + non-rivalrous = public good, open source is a public good, etc.), and then introduce Gratipay in the last minute.

**Comment by whit537** [comment]
@jhibbets Form submitted. Ping me if we need to revise. Headshot when I have it, later this week hopefully ...

**Comment by jhibbets** [comment]
Thank you very much. I think your proposal sounds fine. My honest feedback
is that if it's too much of a sales pitch, it will turn people off. If you
pitch it as an interesting way to solve the problem, then that could work
really well. Thanks for checking in!

Jason

**Comment by whit537** [comment]
Thanks @jhibbets. Maybe I will mention alternatives to Gratipay as well—Liberapay, Open Collective, Bountysource, Patreon, Kickstarter, PayPal.

**Comment by jhibbets** [comment]
I think that would set you nicely. It could be from the perspective, hey,
there are other programs out there like this... examples. And here's what
GratiPay is, the approach we use, and how we do things differently.

**Comment by whit537** [comment]
I wrote a draft for my lightning talk. Working draft here:

https://docs.google.com/document/d/1YLqskSd0SrSqaUWAVhELY0lFZ3tNaeQ3LFU6ES3a_5A/edit?usp=sharing

**Comment by whit537** [comment]
I have slides in HTML, working on converting to PDF. Hitting [issues](http://stackoverflow.com/questions/13154147/how-to-set-safari-print-margins-via-css-to-print-borderless) printing borderless PDF, trying [Weasyprint](weasyprint.org) ...

**Comment by whit537** [comment]
Okay! [Here you go](https://github.com/whit537/openorg/files/544755/chad-whitacre-ATO2016.pdf), @jhibbets. S'okay? If I want to add a slide can I try to sneak that in before Thursday?

**Comment by whit537** [comment]
Also sent in private email.

> Slides look great, thank you.

👍

**Comment by whit537** [comment]
[Very minor update](https://github.com/whit537/openorg/files/546848/chad-whitacre-ATO2016.pdf).

**Comment by whit537** [comment]
Okay! It happened. I'll post video if/when that lands.
