### ISSUE TITLE
Add to definition of "Open Org"

### ISSUE THREAD

**Issue by whit537** [whit537/openorg#8]
Bringing over from private email:

>My thanks to everyone who responded to the OpenOrg community projects worksheet I drafted recently[1]. I've taken a look at all the contributions, and I see that "Definition of Open Organizations" appears to have generated the most interest. So I suggest we begin there.
>
>I've opened a space in our shared Google Drive for us to noodle and play[2]. If I recall correctly, we most interested _not_ in writing a single, definitive definition of open organizations, but rather listing
the characteristics of open organizations and explaining the various ratios in which these might be present in a given organization. So I might suggest we begin with a prompt that looks something like:
>
>"An open organization is one that embraces and demonstrates the following qualities:"
>
>... and then perhaps make a list of the "traits" we deem relevant here, along with an explanatory paragraph about each.
>
>Then, we might compose some additional explanatory text that stresses the "ratio" element of the definition (or the "dial principles," as Rebecca so aptly put it [3]!), as well as something that pertains to the logic of "necessary and sufficient conditions," as Jim has written previously.
>
>Just a few thoughts on possible paths forward. Open (ha!) to others!
>
>What do you think? Can we make this a goal? Perhaps aim to have something polished before the December holidays are upon us? In the new year, then, we could launch a new community resource introducing new readers to the definition and asking for feedback.
>
>Really looking forward to working on this with everyone!
>
>Have fun:
>
>https://docs.google.com/a/redhat.com/document/d/1cKdldNA9wnl67MiS5UGhYzy2IDrCyDRTvXJeDRQ9wnI/edit?usp=sharing
>
>Sincerely,
Bryan
>
>
>[1]
https://docs.google.com/a/redhat.com/document/d/1mtxW6XFO9du-cLOtiETrx8L4nG12fV8XEwrTdvVygLY/edit?usp=sharing
>
>[2]
https://docs.google.com/a/redhat.com/document/d/1cKdldNA9wnl67MiS5UGhYzy2IDrCyDRTvXJeDRQ9wnI/edit?usp=sharing
>
>[3]
http://bryanmmathers.com/wp-content/uploads/2016/05/innovation2-470x165.png

**Comment by semioticrobotic** [comment]
This is going to be really fun.

**Comment by whit537** [comment]
The definition is public and we have a repo! 💃 

https://github.com/opensourceway/open-org-definition
https://opensource.com/open-organization

Closing here ...
